# Generated by Django 2.1.3 on 2018-11-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiexm', '0005_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('CostoPresupuesto', models.CharField(max_length=255)),
                ('CostoReal', models.CharField(max_length=255)),
                ('Tienda', models.CharField(max_length=255)),
                ('NotaAdicional', models.TextField(max_length=100)),
                ('GrupoList', models.CharField(max_length=255)),
            ],
        ),
    ]
