# Generated by Django 2.1.3 on 2018-11-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiexm', '0007_lista'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('NombreSucursal', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Ciudad', models.CharField(max_length=255)),
            ],
        ),
    ]
