# Generated by Django 2.1.3 on 2018-11-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiexm', '0008_tiendafisica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiendaFisica',
        ),
    ]
