# Generated by Django 2.1.3 on 2018-12-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiexm', '0013_tiendaonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='CantidadMax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='CostoPresupuesto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='CostoReal',
            field=models.IntegerField(),
        ),
    ]
